oreja/config/routes.rb
Rails.application.routes.draw do
  root 'user#show'
  
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get '/login', to: "sessions#new"
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  
  resources :users
  resources :episodes
  resources :podcasts
  resources :providers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

oreja/app/models/provider.rb
class Provider < ApplicationRecord
    validates :name, :uniqueness => true
    has_many :podcasts
end

oreja/app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
    @provider = Provider.find_by_name(params[:name])
    @podcasts = @provider.podcasts
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name, :description)
    end
end

oreja/app/helpers/providers_helper.rb
module ProvidersHelper
end

oreja/app/views/providers/_form.html.haml
= form_for(provider) do |f|
  - if provider.errors.any?
    #error_explanation
      %h2
        = pluralize(provider.errors.count, "error")
        prohibited this provider from being saved:
      %ul
        - provider.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit

oreja/app/views/providers/_podcasts_table.html.haml
%table
  %thead
    %tr
      %th Logo
      %th Name
      %th Genre
      %th Summary
      %th{:colspan => "3"}
  %tbody
    - @podcasts.each do |podcast|
      %tr
        %td= link_to(image_tag(podcast.image_url), podcast_path(:id => podcast.id, :name => podcast.name))
        %td= podcast.name
        %td= podcast.genre
        %td= podcast.summary
        -# %td= link_to 'Show', podcast
        %td= link_to 'Edit', edit_podcast_path(podcast)
        %td= link_to 'Destroy', podcast, method: :delete, data: { confirm: 'Are you sure?' }

oreja/app/views/providers/_providers_table.html.haml
%table
  %thead
    %tr
      %th Name
      %th Description
      %th{:colspan => "3"}
  %tbody
    - @providers.each do |provider|
      %tr
        %td= link_to "#{provider.name}", provider_path(:id => provider.id, :name => provider.name)
        %td= provider.description
        %td= link_to 'Show', provider_path(:id => provider.id, :name => provider.name)
        %td= link_to 'Edit', edit_provider_path(provider)
        %td= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' }
%br/

oreja/app/views/providers/edit.html.haml
%h1 Editing Provider
= render 'form', provider: @provider
= link_to 'Show', @provider
|
= link_to 'Back', providers_path

oreja/app/views/providers/index.html.haml
%p#notice= notice
%h1 Providers

= render 'providers_table'
= link_to 'New Provider', new_provider_path

oreja/app/views/providers/new.html.haml
%h1 New Provider
= render 'form', provider: @provider
= link_to 'Back', providers_path

oreja/app/views/providers/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @provider.name
%p
  %strong Description:
  = @provider.description

= render 'podcasts_table'

= link_to 'Edit', edit_provider_path(@provider)
|
= link_to 'Back', providers_path