oreja/config/routes.rb
Rails.application.routes.draw do
  root 'user#show'
  
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get '/login', to: "sessions#new"
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  
  resources :users
  resources :episodes
  resources :podcasts
  resources :providers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

oreja/app/models/podcast.rb
class Podcast < ApplicationRecord
    validates :name, :uniqueness => true
    
    belongs_to :provider, optional: true
    has_many :episodes
    
end

oreja/app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :set_podcast, only: [:show, :edit, :update, :destroy]

  # GET /podcasts
  # GET /podcasts.json
  def index
    @podcasts = Podcast.all
  end

  # GET /podcasts/1
  # GET /podcasts/1.json
  def show
    @podcast = Podcast.find_by_name(params[:name])
    @provider = Provider.find_by(@podcast.provider_id)
    @episodes = @podcast.episodes
  end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
  end

  # GET /podcasts/1/edit
  def edit
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(podcast_params)

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: 'Podcast was successfully created.' }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { render :new }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcasts/1
  # PATCH/PUT /podcasts/1.json
  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { render :show, status: :ok, location: @podcast }
      else
        format.html { render :edit }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast.destroy
    respond_to do |format|
      format.html { redirect_to podcasts_url, notice: 'Podcast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Podcast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def podcast_params
      params.require(:podcast).permit(:name, :genre, :summary)
    end
end

oreja/app/helpers/podcasts_helper.rb
module PodcastsHelper
end

oreja/app/views/podcasts/_episode_table.html.haml
%table
  %thead
    %tr
      %th Name
      %th Description
      %th Duration
      %th Air Date
      %th{:colspan => "3"}
  %tbody
    - @episodes.each do |episode|
      %tr
        %td= link_to(episode.name,episode_path(episode.id))
        %td= episode.description
        %td= episode.display_time("duration") 
        %td= episode.display_time("air_date")
        %td= link_to 'Show', episode
        %td= link_to 'Edit', edit_episode_path(episode)
        %td= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' }

oreja/app/views/podcasts/_form.html.haml
= form_for(podcast) do |f|
  - if podcast.errors.any?
    #error_explanation
      %h2
        = pluralize(podcast.errors.count, "error")
        prohibited this podcast from being saved:
      %ul
        - podcast.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :genre
    = f.text_field :genre
  .field
    = f.label :summary
    = f.text_area :summary
  .actions
    = f.submit

oreja/app/views/podcasts/_podcast_table.html.haml
%table
  %thead
    %tr
      %th Logo
      %th Name
      %th Genre
      %th Summary
      %th{:colspan => "3"}
  %tbody
    - @podcasts.each do |podcast|
      %tr
        %td= link_to(image_tag(podcast.image_url), podcast_path(:id => podcast.id, :name => podcast.name), :id => podcast.id)
        %td= podcast.name
        %td= podcast.genre
        %td= podcast.summary
        %td= link_to 'Show', podcast_path(:id => podcast.id, :name => podcast.name)
        %td= link_to 'Edit', edit_podcast_path(podcast)
        %td= link_to 'Destroy', podcast, method: :delete, data: { confirm: 'Are you sure?' }
%br/

oreja/app/views/podcasts/edit.html.haml
%h1 Editing Podcast
= render 'form', podcast: @podcast
= link_to 'Show', @podcast
|
= link_to 'Back', podcasts_path

oreja/app/views/podcasts/index.html.haml
%p#notice= notice
%h1 Podcasts

= render 'podcast_table'
= link_to 'New Podcast', new_podcast_path

oreja/app/views/podcasts/new.html.haml
%h1 New Podcast
= render 'form', podcast: @podcast
= link_to 'Back', podcasts_path

oreja/app/views/podcasts/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @podcast.name
%p
  %strong Logo:
  = image_tag(@podcast.image_url)
%p
  %strong Genre:
  = @podcast.genre
%p
  %strong Summary:
  = @podcast.summary
%p
  %strong Provider:
  = @provider.name

= render 'episode_table'

= link_to 'Edit', edit_podcast_path(@podcast)
|
= link_to 'Back', podcasts_path