oreja/config/routes.rb
Rails.application.routes.draw do
  root 'user#show'
  
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get '/login', to: "sessions#new"
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  
  resources :users
  resources :episodes
  resources :podcasts
  resources :providers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

oreja/app/models/episode.rb
class Episode < ApplicationRecord
    validates_uniqueness_of :name
    belongs_to :podcast, optional: true
    
    def display_time(type)
        if type == "duration"
            self.duration.nil? ? "Unknown" : self.duration.strftime("%H:%M:%S")
        else 
            self.air_date.nil? ? "Unknown" : self.air_date.to_formatted_s(:long)
        end
    end
end

oreja/app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:name, :description, :duration, :air_date)
    end
end

oreja/app/helpers/episodes_helper.rb
module EpisodesHelper
end

oreja/app/views/episodes/_form.html.haml
= form_for(episode) do |f|
  - if episode.errors.any?
    #error_explanation
      %h2
        = pluralize(episode.errors.count, "error")
        prohibited this episode from being saved:
      %ul
        - episode.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :duration
    = f.time_select :duration
  .field
    = f.label :air_date
    = f.datetime_select :air_date
  .actions
    = f.submit

oreja/app/views/episodes/edit.html.haml
%h1 Editing Episode
= render 'form', episode: @episode
= link_to 'Show', @episode
|
= link_to 'Back', episodes_path

oreja/app/views/episodes/index.html.haml
%p#notice= notice
%h1 Episodes
%table
  %thead
    %tr
      %th Name
      %th Description
      %th Duration
      %th Air date
      %th Podcast
      %th{:colspan => "3"}
  %tbody
    - @episodes.each do |episode|
      %tr
        %td= episode.name
        %td= episode.description
        %td= episode.duration 
        -# strftime("%H:%M:%S")
        %td= episode.air_date 
        -# to_formatted_s(:long)
        %td= episode.podcast.name
        %td= link_to 'Show', episode
        %td= link_to 'Edit', edit_episode_path(episode)
        %td= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Episode', new_episode_path

oreja/app/views/episodes/new.html.haml
%h1 New Episode
= render 'form', episode: @episode
= link_to 'Back', episodes_path

oreja/app/views/episodes/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @episode.name
%p
  %strong Description:
  = @episode.description
%p
  %strong Duration:
  = @episode.display_time("duration") 
%p
  %strong Air date:
  = @episode.display_time("air_date") 
  
= link_to 'Edit', edit_episode_path(@episode)
|
= link_to 'Back', episodes_path