oreja/config/routes.rb
Rails.application.routes.draw do
  root 'user#show'
  
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get '/login', to: "sessions#new"
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  
  resources :users
  resources :episodes
  resources :podcasts
  resources :providers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

oreja/app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .container
      = link_to("Oreja", user_path(current_user), id: "Logo") if !current_user.nil?
      = link_to("Oreja", login_path, id: "Logo") if current_user.nil?

      %nav
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Providers", providers_path
          %li= link_to "Podcasts", podcasts_path
          - if logged_in?
            %li= link_to "Users", '#'
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li
                  = link_to "Log out", logout_path, method: "delete"
          - else
            %li= link_to "Log in", login_path

oreja/app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Oreja
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
  
    - if flash[:success]
      #notice.message= flash[:success]
    - if flash[:danger]
      #notice.message= flash[:danger]
      
    .container
    = yield